"use client";

import { useEffect, useMemo, useState } from "react";
import type { SupabaseClient, User } from "@supabase/supabase-js";
import { Code, KeyRound, LoaderCircle } from "lucide-react";
import SourcesPanel, { type Busy } from "@/components/SourcesPanel";
import ChatPanel, { type Message } from "@/components/ChatPanel";
import SettingsModal from "@/components/SettingsModal";
import NotebookBar from "@/components/NotebookBar";
import AccountButton from "@/components/AccountButton";
import { BUTTON, ICON_BUTTON } from "@/components/ui";
import { chunkText } from "@/lib/chunk";
import { topK } from "@/lib/vector";
import { localStore } from "@/lib/store";
import { cloudEnabled, cloudStore, getSupabase, mightBeSignedIn } from "@/lib/cloud";
import type { Notebook, RetrievedChunk, Source, SourceType } from "@/lib/types";

async function readPdf(file: File): Promise<string> {
  // Parsed in the browser: no upload, so no server size limit. Loaded on demand to keep the page bundle small.
  const { extractText, getDocumentProxy } = await import("unpdf");
  const pdf = await getDocumentProxy(new Uint8Array(await file.arrayBuffer()));
  const { text } = await extractText(pdf, { mergePages: true });
  if (!text.trim()) throw new Error("No extractable text found — this PDF is likely a scan (images only).");
  return text;
}

// Prebuilt demo (public/demo-notebook.json): a public-domain NASA video, already embedded, so it loads instantly.
const DEMO_VIDEO = "LTokm19iXu8";
const DEMO_QUESTIONS = [
  "How big is Webb's primary mirror, and why does it have to fold?",
  "Why were the mirrors made the “wrong” shape on purpose?",
  "How do engineers align the mirrors once Webb is in space?",
];
// The demo file also carries real answers to DEMO_QUESTIONS, generated by this app's own pipeline,
// so the first clicks are instant and don't spend the shared key's small free quota.
type Demo = Omit<Source, "id" | "notebookId" | "type" | "addedAt"> & {
  answers: Record<string, { text: string; citations: RetrievedChunk[] }>;
};
let demoFile: Promise<Demo> | undefined;
const loadDemo = () => (demoFile ??= fetch("/demo-notebook.json").then((r) => r.json()));

const GENERAL_QUESTIONS = [
  "Summarize the key points",
  "What are the most surprising claims, and what supports them?",
  "List the key moments with timestamps",
];

const ACTIVE_KEY = "cogniflow:notebook"; // last-open notebook, a per-browser convenience
function readActive(): string | null {
  try {
    return localStorage.getItem(ACTIVE_KEY);
  } catch {
    return null;
  }
}

export default function Home() {
  const [notebooks, setNotebooks] = useState<Notebook[]>([]);
  const [active, setActive] = useState("");
  const [allSources, setAllSources] = useState<Source[]>([]);
  const [chats, setChats] = useState<Record<string, Message[]>>({}); // per notebook, this tab only
  const [busy, setBusy] = useState<Busy>(null);
  const [mobileView, setMobileView] = useState<"sources" | "chat">("chat"); // below lg, one panel at a time
  const [asking, setAsking] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [apiKey, setApiKey] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false);
  // Signed in: notebooks sync to Supabase. Signed out (or no Supabase configured): this browser only.
  const [supabase, setSupabase] = useState<SupabaseClient | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [authReady, setAuthReady] = useState(false); // resolved on mount: immediately when no session can exist
  const [localCount, setLocalCount] = useState(0); // sources in this browser that could move into the account
  const store = useMemo(() => (user && supabase ? cloudStore(supabase) : localStore), [user?.id, supabase]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!mightBeSignedIn()) setAuthReady(true); // show local notebooks now; supabase-js still loads for "Sign in"
    if (!cloudEnabled) return;
    let unsubscribe = () => {};
    void getSupabase().then(async (client) => {
      setSupabase(client);
      unsubscribe = client.auth.onAuthStateChange((_event, session) => setUser(session?.user ?? null)).data.subscription.unsubscribe;
      setUser((await client.auth.getSession()).data.session?.user ?? null);
      setAuthReady(true);
    });
    return () => unsubscribe();
  }, []);

  async function reload() {
    setLoaded(false);
    try {
      const { notebooks, sources } = await store.loadAll();
      setNotebooks(notebooks);
      setAllSources(sources);
      setChats({});
      const last = readActive();
      setActive(notebooks.some((n) => n.id === last) ? last! : notebooks[0].id);
      setLocalCount(user ? (await localStore.loadAll()).sources.length : 0);
    } catch (err) {
      setNotebooks([{ id: "offline", name: "Unavailable", createdAt: 0 }]);
      setActive("offline");
      showError("offline", err, "Could not load your notebooks.");
    }
    setLoaded(true);
  }

  useEffect(() => {
    if (authReady) void reload();
  }, [authReady, store]); // eslint-disable-line react-hooks/exhaustive-deps

  /** Copy this browser's notebooks into the signed-in account, then clear them locally. */
  async function moveLocalToAccount() {
    setBusy({ kind: "text", status: "Moving your notebooks into your account…" });
    await guard(async () => {
      const local = await localStore.loadAll();
      const ids = new Map(local.notebooks.map((n) => [n.id, crypto.randomUUID()]));
      for (const n of local.notebooks)
        if (local.sources.some((s) => s.notebookId === n.id)) await store.saveNotebook({ ...n, id: ids.get(n.id)! });
      for (const s of local.sources) await store.saveSource({ ...s, id: crypto.randomUUID(), notebookId: ids.get(s.notebookId!)! });
      await localStore.clear();
      await reload();
    });
    setBusy(null);
  }

  useEffect(() => {
    try {
      if (active) localStorage.setItem(ACTIVE_KEY, active);
    } catch {
      // storage unavailable (private mode); the default notebook opens next time
    }
  }, [active]);

  const sources = allSources.filter((s) => s.notebookId === active);
  const messages = chats[active] ?? [];

  async function request(path: string, body: FormData | object): Promise<Response> {
    const form = body instanceof FormData;
    const res = await fetch(path, {
      method: "POST",
      headers: { ...(form ? {} : { "Content-Type": "application/json" }), ...(apiKey ? { "x-gemini-key": apiKey } : {}) },
      body: form ? body : JSON.stringify(body),
    });
    if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error ?? `Request failed (${res.status}).`);
    return res;
  }
  const post = async (path: string, body: FormData | object) => (await request(path, body)).json();

  async function embedDocuments(texts: string[], onProgress: (done: number) => void): Promise<number[][]> {
    const out: number[][] = [];
    for (let i = 0; i < texts.length; i += 96) {
      onProgress(i);
      out.push(...(await post("/api/embed", { texts: texts.slice(i, i + 96), taskType: "RETRIEVAL_DOCUMENT" })).vectors);
    }
    return out;
  }

  // Messages are addressed by notebook, so a reply streaming in after a switch lands in the right chat.
  const setChat = (nb: string, fn: (ms: Message[]) => Message[]) => setChats((c) => ({ ...c, [nb]: fn(c[nb] ?? []) }));
  function addMessage(nb: string, m: Omit<Message, "id">): string {
    const id = crypto.randomUUID();
    setChat(nb, (ms) => [...ms, { ...m, id }]);
    return id;
  }
  const updateMessage = (nb: string, id: string, patch: Partial<Message>) =>
    setChat(nb, (ms) => ms.map((m) => (m.id === id ? { ...m, ...patch } : m)));
  const showError = (nb: string, err: unknown, fallback: string) =>
    addMessage(nb, { role: "assistant", text: err instanceof Error ? err.message : fallback, error: true });
  // Store calls can fail once they go over the network; surface that in the chat.
  async function guard(fn: () => Promise<void>) {
    const nb = active;
    try {
      await fn();
    } catch (err) {
      showError(nb, err, "Could not save your change.");
    }
  }

  type Loaded = { title: string; texts: string[]; times?: number[]; url?: string; videoId?: string };

  async function ingest(type: SourceType, status: string, load: () => Promise<Loaded>) {
    const nb = active;
    setBusy({ kind: type, status });
    try {
      const { texts, times, ...meta } = await load();
      const vectors = await embedDocuments(texts, (done) =>
        setBusy({ kind: type, status: `Indexing “${meta.title}”… ${done ? `${done}/${texts.length}` : `${texts.length} passages`}` })
      );
      const source: Source = {
        id: crypto.randomUUID(),
        notebookId: nb,
        type,
        addedAt: Date.now(),
        ...meta,
        chunks: texts.map((text, i) => ({ text, vector: vectors[i], startTimeSec: times?.[i] })),
      };
      await store.saveSource(source);
      setAllSources((prev) => [...prev, source]);
      setMobileView("chat");
    } catch (err) {
      showError(nb, err, "Couldn't add that source.");
    } finally {
      setBusy(null);
    }
  }

  const handleAddYouTube = (url: string) =>
    ingest("youtube", "Fetching the transcript… long videos can take a minute", async () => {
      const j = await post("/api/youtube", { url });
      const chunks = j.chunks as { text: string; startTimeSec: number }[];
      return {
        title: j.title,
        url: j.url,
        videoId: j.videoId,
        texts: chunks.map((c) => c.text),
        times: chunks.map((c) => c.startTimeSec),
      };
    });

  const handleAddFile = (file: File, kind: "pdf" | "audio") =>
    ingest(kind, kind === "pdf" ? "Reading the PDF…" : "Transcribing the audio…", async () => {
      if (kind === "pdf") return { title: file.name.replace(/\.pdf$/i, ""), texts: chunkText(await readPdf(file)) };
      const form = new FormData();
      form.append("file", file);
      const j = await post("/api/audio", form);
      return { title: j.title, texts: chunkText(j.text) };
    });

  const handleAddText = (title: string, text: string) => ingest("text", "Indexing…", async () => ({ title, texts: chunkText(text) }));

  async function handleTryDemo() {
    const nb = active;
    setBusy({ kind: "youtube", status: "Loading the demo…" });
    try {
      const { answers: _answers, ...demo } = await loadDemo();
      const source: Source = { ...demo, id: crypto.randomUUID(), notebookId: nb, type: "youtube", addedAt: Date.now() };
      await store.saveSource(source);
      setAllSources((prev) => [...prev, source]);
      setMobileView("chat");
    } catch (err) {
      showError(nb, err, "Couldn't load the demo.");
    } finally {
      setBusy(null);
    }
  }

  const handleRemove = (id: string) =>
    guard(async () => {
      await store.deleteSource(id);
      setAllSources((prev) => prev.filter((s) => s.id !== id));
    });

  const handleCreateNotebook = () =>
    guard(async () => {
      const notebook = { id: crypto.randomUUID(), name: `Notebook ${notebooks.length + 1}`, createdAt: Date.now() };
      await store.saveNotebook(notebook);
      setNotebooks((n) => [...n, notebook]);
      setActive(notebook.id);
    });

  const handleRenameNotebook = (name: string) =>
    guard(async () => {
      const notebook = notebooks.find((n) => n.id === active);
      if (!notebook || !name.trim()) return;
      const renamed = { ...notebook, name: name.trim().slice(0, 80) };
      await store.saveNotebook(renamed);
      setNotebooks((n) => n.map((x) => (x.id === active ? renamed : x)));
    });

  const handleDeleteNotebook = () =>
    guard(async () => {
      if (notebooks.length < 2) return;
      const id = active;
      await store.deleteNotebook(id, sources.map((s) => s.id));
      const rest = notebooks.filter((n) => n.id !== id);
      setNotebooks(rest);
      setAllSources((prev) => prev.filter((s) => s.notebookId !== id));
      setChats(({ [id]: _dropped, ...c }) => c);
      setActive(rest[0].id);
    });

  async function handleAsk(question: string) {
    const nb = active;
    if (DEMO_QUESTIONS.includes(question) && sources.length && sources.every((s) => s.videoId === DEMO_VIDEO)) {
      const cached = (await loadDemo().catch(() => undefined))?.answers[question];
      if (cached) {
        addMessage(nb, { role: "user", text: question });
        addMessage(nb, { role: "assistant", ...cached });
        return;
      }
    }
    const history = messages.filter((m) => !m.error).slice(-6).map(({ role, text }) => ({ role, text: text.slice(0, 4000) }));
    addMessage(nb, { role: "user", text: question });
    setAsking(true);
    try {
      // Follow-ups are rewritten server-side into a standalone query; search with that.
      const { vectors, query } = await post("/api/embed", { texts: [question], taskType: "RETRIEVAL_QUERY", history });
      const hits = topK(vectors[0], query, sources, 6);
      if (!hits.length) throw new Error("No indexed sources found. Re-add a source (your browser storage may have been cleared).");

      const citations: RetrievedChunk[] = hits.map((h, i) => ({
        n: i + 1,
        text: h.chunk.text,
        sourceTitle: h.source.title,
        sourceType: h.source.type,
        sourceUrl: h.source.url,
        videoId: h.source.videoId,
        startTimeSec: h.chunk.startTimeSec,
      }));
      const res = await request("/api/ask", { question, chunks: citations, history });
      const reader = res.body!.pipeThrough(new TextDecoderStream()).getReader();
      let text = "";
      let id: string | undefined;
      try {
        for (let r = await reader.read(); !r.done; r = await reader.read()) {
          text += r.value;
          if (id) updateMessage(nb, id, { text });
          else id = addMessage(nb, { role: "assistant", text, citations });
        }
      } catch (err) {
        if (!id) throw err;
        updateMessage(nb, id, { text: `${text}\n\n_(The answer was cut off. Please ask again.)_` });
      }
      if (!id) throw new Error("The model returned an empty answer.");
    } catch (err) {
      showError(nb, err, "Something went wrong.");
    } finally {
      setAsking(false);
    }
  }

  const hasSources = sources.some((s) => s.chunks.length > 0);
  const suggestions = sources.some((s) => s.videoId === DEMO_VIDEO) ? DEMO_QUESTIONS : GENERAL_QUESTIONS;

  return (
    <main className="mx-auto flex h-dvh max-w-7xl flex-col">
      <header className="flex h-16 shrink-0 items-center justify-between gap-2 border-b border-border px-3 sm:px-4">
        <a href="/" className="flex items-center gap-2.5 rounded-lg text-lg font-semibold tracking-tight focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/icon.svg" alt="" className="size-8 rounded-lg" />
          Cogniflow
        </a>

        <div className="flex items-center gap-1.5">
          {supabase && authReady && (
            <AccountButton
              email={user?.email}
              onSignIn={(provider) =>
                void supabase!.auth.signInWithOAuth({ provider, options: { redirectTo: window.location.origin } })
              }
              onSignOut={() => void supabase!.auth.signOut()}
            />
          )}
          <button onClick={() => setSettingsOpen(true)} className={BUTTON} aria-label="Gemini API key settings">
            <KeyRound className="size-4" aria-hidden />
            <span className="hidden sm:inline">{apiKey ? "Your key" : "API key"}</span>
            {apiKey && <span className="size-2 rounded-full bg-accent" aria-hidden />}
          </button>
          <a
            href="https://github.com/shihabcodes/Cogniflow_AI"
            target="_blank"
            rel="noreferrer"
            className={ICON_BUTTON}
            aria-label="Source code on GitHub"
            title="Source code on GitHub"
          >
            <Code className="size-5" aria-hidden />
          </a>
        </div>
      </header>

      {!loaded ? (
        <div className="flex flex-1 items-center justify-center text-muted-foreground" role="status" aria-label="Loading">
          <LoaderCircle className="size-6 animate-spin" aria-hidden />
        </div>
      ) : (
        <>
          <div role="tablist" aria-label="View" className="mx-3 mt-3 grid grid-cols-2 gap-1 rounded-lg bg-muted p-1 lg:hidden">
            {(["sources", "chat"] as const).map((v) => (
              <button
                key={v}
                role="tab"
                aria-selected={mobileView === v}
                onClick={() => setMobileView(v)}
                className={`min-h-10 cursor-pointer rounded-md text-sm font-medium transition-colors duration-150 ${
                  mobileView === v ? "bg-card shadow-sm" : "text-muted-foreground"
                }`}
              >
                {v === "sources" ? `Sources (${sources.length})` : "Chat"}
              </button>
            ))}
          </div>

          <div className="grid min-h-0 flex-1 gap-4 p-3 sm:p-4 lg:grid-cols-[360px_1fr]">
            <div className={`flex min-h-0 flex-col gap-3 ${mobileView === "chat" ? "max-lg:hidden" : ""}`}>
              {user && localCount > 0 && (
                <div className="flex items-center justify-between gap-2 rounded-xl bg-accent-soft px-3 py-2 text-sm">
                  <span>
                    {localCount} source{localCount > 1 ? "s" : ""} saved in this browser only.
                  </span>
                  <button disabled={!!busy} onClick={() => void moveLocalToAccount()} className={`${BUTTON} shrink-0`}>
                    Move to account
                  </button>
                </div>
              )}
              <NotebookBar
                notebooks={notebooks}
                activeId={active}
                sourceCount={sources.length}
                disabled={!!busy || asking}
                onSelect={setActive}
                onCreate={handleCreateNotebook}
                onRename={handleRenameNotebook}
                onDelete={handleDeleteNotebook}
              />
              <div className="min-h-0 flex-1">
                <SourcesPanel
                  sources={sources}
                  busy={busy}
                  onAddYouTube={handleAddYouTube}
                  onAddFile={handleAddFile}
                  onAddText={handleAddText}
                  onRemove={handleRemove}
                />
              </div>
            </div>
            <div className={`min-h-0 ${mobileView === "sources" ? "max-lg:hidden" : ""}`}>
              <ChatPanel
                messages={messages}
                asking={asking}
                hasSources={hasSources}
                suggestions={suggestions}
                onAsk={handleAsk}
                onTryDemo={busy ? undefined : handleTryDemo}
              />
            </div>
          </div>
        </>
      )}

      <SettingsModal isOpen={settingsOpen} onClose={() => setSettingsOpen(false)} apiKey={apiKey} onSaveKey={setApiKey} />

      <footer className="shrink-0 px-4 pb-3 text-center text-xs text-muted-foreground">
        Open source ·{" "}
        <a href="https://github.com/shihabcodes" target="_blank" rel="noreferrer" className="underline-offset-2 hover:text-foreground hover:underline">
          built by @shihabcodes
        </a>{" "}
        · your sources stay in your browser unless you sign in
      </footer>
    </main>
  );
}
